#!/usr/bin/env python3
"""Dependency Audit Agent

Monitors Cargo.toml for outdated or insecure dependencies.
Checks against crates.io API for latest stable versions.
"""

import json
import os
import re
import urllib.request
from datetime import datetime, timezone
from pathlib import Path


def parse_cargo_toml():
    """Extract dependencies from Cargo.toml."""
    cargo = Path('Cargo.toml')
    if not cargo.exists():
        return []

    content = cargo.read_text(encoding='utf-8')
    deps = []

    in_deps = False
    for line in content.split('\n'):
        if line.strip() == '[dependencies]':
            in_deps = True
            continue
        if line.strip().startswith('[') and in_deps:
            in_deps = False
        if in_deps and '=' in line and not line.strip().startswith('#'):
            match = re.match(r'^([a-zA-Z0-9_-]+)\s*=\s*"([^"]+)"', line)
            if match:
                deps.append({"name": match.group(1), "version": match.group(2)})

    return deps


def fetch_latest_version(crate_name):
    """Query crates.io for latest version."""
    try:
        url = f"https://crates.io/api/v1/crates/{crate_name}"
        req = urllib.request.Request(url, headers={'User-Agent': 'ramshield-helper/0.2.0'})
        with urllib.request.urlopen(req, timeout=5) as response:
            data = json.loads(response.read())
            return data.get('crate', {}).get('max_version', 'unknown')
    except (urllib.error.URLError, json.JSONDecodeError, TimeoutError) as e:
        return f"error: {e}"


def audit_dependencies():
    """Audit dependencies and report outdated ones."""
    deps = parse_cargo_toml()
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    report_lines = [
        "# Dependency Audit Report",
        "",
        f"**Generated:** {timestamp}",
        f"**Total dependencies:** {len(deps)}",
        "",
        "---",
        "",
        "## Crates",
        "",
        "| Crate | Current | Latest | Status |",
        "|-------|---------|--------|--------|"
    ]

    outdated = 0
    for dep in deps:
        latest = fetch_latest_version(dep['name'])
        if 'error' in latest or 'unknown' in latest:
            status = "?"
        elif current_strip(dep['version']) == current_strip(latest):
            status = "current"
        else:
            status = "OUTDATED"
            outdated += 1
        report_lines.append(f"| {dep['name']} | {dep['version']} | {latest} | {status} |")

    report_lines.extend([
        "",
        f"**Outdated crates:** {outdated}",
        "",
        "---",
        "",
        "*Generated by RamShield Helper Agent - Dependency Audit*"
    ])

    output = Path('docs') / 'DEPENDENCY_AUDIT.md'
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text('\n'.join(report_lines), encoding='utf-8')
    print(f"Updated {output}")


def current_strip(version):
    """Remove pre-release suffix for comparison."""
    return re.sub(r'-\w+', '', version)


def main():
    workspace = os.environ.get(
        'GITHUB_WORKSPACE',
        str(Path(__file__).parent.parent.parent)
    )
    os.chdir(workspace)
    audit_dependencies()


if __name__ == '__main__':
    main()