#!/usr/bin/env python3
"""HTML Automation Dashboard Generator

Reads various Markdown reports (AGENT_REPORT, DEPENDENCY_AUDIT, HEALTH_DASHBOARD,
CONTROL_CENTER) and compiles them into a single, structured HTML dashboard.
"""

import os
import re
import json
from datetime import datetime, timezone
from pathlib import Path


def md_to_html_section(md_content, title):
    """Converts a Markdown string to an HTML section with basic formatting."""
    html_content = f"<h2>{title}</h2>\n"
    html_content += "<div class=\"markdown-body\">\n"
    # Single pass: paragraphs first, then line breaks in remaining lines
    content = md_content
    content = content.replace('\n---\n', '\n<hr>\n')
    content = content.replace('# ', '<h3>')
    content = content.replace('**', '<strong>')
    paragraphs = content.split('\n\n')
    content = '</p><p>'.join(p.replace('\n', '<br>') for p in paragraphs)
    html_content += content
    html_content += "</div>\n"
    return html_content


def read_report(file_path):
    """Safely reads the content of a Markdown report file."""
    try:
        return Path(file_path).read_text(encoding='utf-8')
    except (FileNotFoundError, UnicodeDecodeError, OSError):
        return f"_Report not found or unreadable: {file_path}_"


def generate_html_dashboard(workspace_root):
    """Generates the main HTML automation dashboard."""
    os.chdir(workspace_root)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Read individual Markdown reports
    agent_report_md = read_report('docs/AGENT_REPORT.md')
    dependency_audit_md = read_report('docs/DEPENDENCY_AUDIT.md')
    health_dashboard_md = read_report('docs/HEALTH_DASHBOARD.md')
    control_center_md = read_report('docs/CONTROL_CENTER.md')

    # Basic HTML structure
    html_output = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RamShield Automation Dashboard</title>
    <style>
        body {{ font-family: sans-serif; margin: 20px; background-color: #1e1e1e; color: #d4d4d4; }}
        h1, h2, h3 {{ color: #569cd6; border-bottom: 1px solid #333; padding-bottom: 5px; margin-top: 20px; }}
        .container {{ max-width: 1200px; margin: auto; background-color: #252526; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.5); }}
        .markdown-body {{ background-color: #1e1e1e; padding: 15px; border-radius: 4px; margin-bottom: 15px; border: 1px solid #333; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
        th, td {{ border: 1px solid #444; padding: 8px; text-align: left; }}
        th {{ background-color: #333; color: #fff; }}
        code {{ background-color: #333; padding: 2px 4px; border-radius: 3px; font-family: monospace; color: #ce9178; }}
        pre {{ background-color: #000; padding: 10px; border-radius: 4px; overflow-x: auto; color: #dcdcdc; }}
        strong {{ color: #9cdcfe; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>RamShield Automation Control Center & Dashboard</h1>
        <p><em>Generated: {timestamp}</em></p>
        <hr>

        {md_to_html_section(control_center_md, "Agent Control Center")}
        {md_to_html_section(health_dashboard_md, "Project Health Overview")}
        {md_to_html_section(agent_report_md, "Helper Agent Latest Report")}
        {md_to_html_section(dependency_audit_md, "Dependency Audit Summary")}

        <p style="text-align: center; margin-top: 30px; font-size: 0.8em; color: #888;"><em>Generated by RamShield HTML Dashboard Agent v0.4.0</em></p>
    </div>
</body>
</html>
"""
    output_path = Path('docs') / 'AUTOMATION_DASHBOARD.html'
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html_output, encoding='utf-8')
    print(f"Generated HTML dashboard: {output_path}")


def main():
    workspace = os.environ.get(
        'GITHUB_WORKSPACE',
        str(Path(__file__).parent.parent.parent)
    )
    generate_html_dashboard(workspace)


if __name__ == '__main__':
    main()