#!/usr/bin/env python3
"""Junior Engineer Agent
Scans codebase, identifies TODOs, generates reports, and updates documentation.
Inspired by RamShield's enterprise structure and Rust 2021 standards."""

import os
import re
from datetime import datetime, timezone
from pathlib import Path


def find_todos(root_path="src", extensions=("rs", "md", "toml", "sh")):
    """Scan files for TODO, FIXME, and HACK comments."""
    todos = []
    pattern = re.compile(r'(//|<!--|#)\s*(TODO|FIXME|HACK):?\s*(.+)', re.IGNORECASE)
    for ext in extensions:
        for path in Path(root_path).rglob(f"*.{ext}"):
            try:
                content = path.read_text(encoding='utf-8')
                for match in pattern.finditer(content):
                    comment, kind, text = match.groups()
                    todos.append({
                        "file": str(path),
                        "line": content[:match.start()].count('\n') + 1,
                        "kind": kind.upper(),
                        "text": text.strip()[:100]
                    })
            except (UnicodeDecodeError, OSError):
                continue
    return todos


def count_metrics(root_path="src"):
    """Analyze code structure."""
    metrics = {"files": 0, "lines": 0, "blank_lines": 0, "comment_lines": 0}
    for path in Path(root_path).rglob("*.rs"):
        try:
            content = path.read_text(encoding='utf-8')
            metrics["files"] += 1
            lines = content.split('\n')
            metrics["lines"] += len(lines)
            metrics["blank_lines"] += sum(1 for line in lines if not line.strip())
            metrics["comment_lines"] += sum(1 for line in lines if line.strip().startswith('//'))
        except (UnicodeDecodeError, OSError):
            continue
    return metrics


def generate_report(workspace_root):
    """Generate dashboard report."""
    os.chdir(workspace_root)
    todos = find_todos()
    metrics = count_metrics()
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    report = f"""# Junior Engineer Agent Report

**Generated:** {timestamp}
**Branch:** `feature/ramshield-advanced`

---

## Codebase Metrics

| Metric | Value |
|--------|-------|
| Rust files | {metrics['files']} |
| Total lines | {metrics['lines']:,} |
| Comment lines | {metrics['comment_lines']:,} |
| Active TODOs | {sum(1 for t in todos if t['kind'] == 'TODO')} |
| Active FIXME | {sum(1 for t in todos if t['kind'] == 'FIXME')} |

---

## Outstanding TODOs ({len(todos)} total)

"""
    for todo in todos[:20]:
        report += f"- **{todo['kind']}** in `{todo['file']}:{todo['line']}` -- {todo['text']}\n"

    if len(todos) > 20:
        report += f"\n*... and {len(todos) - 20} more*\n"

    report += """
---

## RamShield Architecture

- Engine: Async Tokio + batch-first pipeline
- Storage: Sharded DashMap with TTL wheel
- Detection: EWMA plus promotion filter
- Forecasting: Holt-Winters plus Shannon entropy
- Dashboard: Axum HTTP plus SSE streaming
- IPC: TCP JSON protocol with batch APIs

---

*Generated by Junior Engineer Agent v0.1.0*
"""
    output = Path('docs') / 'AGENT_REPORT.md'
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding='utf-8')
    print(f"Updated {output}")


def main():
    workspace = os.environ.get('GITHUB_WORKSPACE', str(Path(__file__).parent.parent.parent))
    generate_report(workspace)


if __name__ == '__main__':
    main()