[package]
name = "ramshield-config"
version = "0.1.0"
edition = "2024"

[dependencies]
ramshield-types = { path = "../ramshield-types" }
serde = { version = "1", features = ["derive"] }
toml = "1"
arc-swap = "1"
anyhow = "1"
argon2 = { version = "0.5", features = ["std"] }

[dev-dependencies]
serial_test = "3"

[lints]
workspace = true
